// <auto-generated />
using CopaHas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CopaHas.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CopaHas.Models.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TB_ESTADIOS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidade = 50000,
                            Cidade = "Sao Paulo",
                            Nome = "Neo Quimica Arena"
                        },
                        new
                        {
                            Id = 2,
                            Capacidade = 80000,
                            Cidade = "Sao Paulo",
                            Nome = "Morumbis"
                        },
                        new
                        {
                            Id = 3,
                            Capacidade = 40000,
                            Cidade = "Sao Paulo",
                            Nome = "Chiqueiro"
                        },
                        new
                        {
                            Id = 4,
                            Capacidade = 67676,
                            Cidade = "Sao Paulo",
                            Nome = "Siri boy Arena"
                        },
                        new
                        {
                            Id = 5,
                            Capacidade = 80000,
                            Cidade = "Paris",
                            Nome = "Parque dos principes"
                        },
                        new
                        {
                            Id = 6,
                            Capacidade = 40000,
                            Cidade = "Salvador",
                            Nome = "Fonte Nova"
                        },
                        new
                        {
                            Id = 7,
                            Capacidade = 77777,
                            Cidade = "Sao Paulo",
                            Nome = "Aura Stadium"
                        });
                });

            modelBuilder.Entity("CopaHas.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroCamisa")
                        .HasColumnType("int");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_JOGADORES");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Hugo Souza",
                            NumeroCamisa = 1,
                            Posicao = "Goleiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Cássio",
                            NumeroCamisa = 12,
                            Posicao = "Goleiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Rafael",
                            NumeroCamisa = 23,
                            Posicao = "Goleiro",
                            SelecaoId = 0,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Fábio",
                            NumeroCamisa = 1,
                            Posicao = "Goleiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Fagner",
                            NumeroCamisa = 23,
                            Posicao = "Lateral Direito",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Samuel Xavier",
                            NumeroCamisa = 2,
                            Posicao = "Lateral Direito",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Ayrton Lucas",
                            NumeroCamisa = 6,
                            Posicao = "Lateral Esquerdo",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Reinaldo",
                            NumeroCamisa = 6,
                            Posicao = "Lateral Esquerdo",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Geromel",
                            NumeroCamisa = 3,
                            Posicao = "Zagueiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Kannemann",
                            NumeroCamisa = 4,
                            Posicao = "Zagueiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Nino",
                            NumeroCamisa = 33,
                            Posicao = "Zagueiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Fabrício Bruno",
                            NumeroCamisa = 15,
                            Posicao = "Zagueiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            Nome = "André",
                            NumeroCamisa = 7,
                            Posicao = "Volante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            Nome = "João Gomes",
                            NumeroCamisa = 35,
                            Posicao = "Volante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Thiago Maia",
                            NumeroCamisa = 8,
                            Posicao = "Volante",
                            SelecaoId = 0,
                            Status = 2
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Arrascaeta",
                            NumeroCamisa = 14,
                            Posicao = "Meia",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Ganso",
                            NumeroCamisa = 10,
                            Posicao = "Meia",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Cristiano Ronaldo",
                            NumeroCamisa = 7,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 2
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Pedro",
                            NumeroCamisa = 9,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Gabriel Barbosa",
                            NumeroCamisa = 10,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Calleri",
                            NumeroCamisa = 9,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
